name: Download File from URL

on:
  workflow_dispatch: # اجرای دستی workflow

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Download File
        run: |
          curl -L "https://uupload.ir/view/untitled-1_gut7.txt/"
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add downloaded file" || echo "No changes to commit"
          git push
